apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
  namespace: u
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      restartPolicy: Always  # Измените на Always
      containers:
        - name: php-fpm
          image: php:8.2-fpm
          ports:
            - containerPort: 9000
          workingDir: /var/www
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_port
            - name: DB_DRIVER
              value: "pdo_pgsql"
            - name: DB_ADAPTER
              value: "pgsql"
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_password
          volumeMounts:
            - name: www-data
              mountPath: /var/www
      initContainers:
        - name: install-dependencies
          image: php:8.2-fpm
          workingDir: /var/www
          command: ["/bin/sh", "-c"]
          args:
            - apt-get update &&
              apt-get install -y libpq-dev curl &&
              docker-php-ext-install pdo pdo_pgsql &&
              curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
              composer install &&
              true
          volumeMounts:
            - name: www-data
              mountPath: /var/www
      volumes:
        - name: www-data
          hostPath:
            path: /var/www
