apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: u
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always  # Измените на Always
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www-data
              mountPath: /var/www
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: www-data
          emptyDir: {}  # Если хотите использовать emptyDir, иначе уберите
        - name: nginx-config
          configMap:
            name: nginx-config
