apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  DATABASE_HOST: "otus-db-postgresql.default.svc.cluster.local"
  DATABASE_PORT: "5433"
  DATABASE_NAME: "otus_user_api"
