apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: ratiborro/otus-user-api:latest
          workingDir: /var/www/public
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-cm
              subPath: default.conf
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: default.conf
            name: nginx-cm
          name: nginx-cm
