apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: ratiborro/otus-user-api:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-credentials
#          volumeMounts:
#            - mountPath: /var/www
#              name: php-volume
#      volumes:
#        - name: php-volume
#          persistentVolumeClaim:
#            claimName: php-claim