apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/www # Путь на хосте Minikube
